# Generated by Django 5.0 on 2024-01-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_batch_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='c',
            field=models.IntegerField(null=True),
        ),
    ]
