# Generated by Django 5.0 on 2024-01-10 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
        ('student', '0004_remove_student_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='advisor.advisor'),
        ),
    ]
