# Generated by Django 5.0 on 2024-01-10 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
        ('student', '0005_student_advisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advisor.advisor'),
        ),
    ]
